#+TITLE: Curriculum Vitae
#+OPTIONS: toc:nil
#+LaTeX_CLASS: koma-article

* CONTACT

email: bruce.graham@gmail.com
cellular: 0027-72-091-6687

* SUMMARY

Bruce is a BSc (Math, Operational Research) graduate with further studies in financial engineering and business reporting, through the Actuarial Society of South Africa.

Bruce has acted as his own investment manager since 2017 where he has developed a growing knowledge of global investment opportunities.

Bruce's entreprenarial flare led him to become involved in an ice cream wholesaler startup in Cape Town where he put his knowledge of modelling to use to anticipate business profitability and cash flow. These exercises eventually led to savings in the tens of millions of rands for the company.
       
* EDUCATION

- Actuarial Student Fin. math (FB), Business reporting (FB)
Actuarial Society of South Africa, Cape Town

- Bachelor of Science in Operational Research, Mathematics, Statistics
University of South Africa, Pretoria

* WORK EXPERIENCE

** Entrepreneur/Consultant -  2011-2017

Wilfredo’s Ice Cream Company
  - 2017 to now Bruce has administered and tended to his personal investment fund. He has also raised his family where he has a daughter with special needs.
  - 2012-2017 Bruce administered the business and guided the direction of the business, spending his free time building a spreadsheet model to anticipate cashflow and profitability of the business.
  - 2012 With his business partner, they produced ice cream and delivered it.
  - 2011 Bruce performed product R&D and  established a factory. He also researched a financial reporting system and performed the bookkeeping.

* PROJECTS

** Costing and Profit spreadsheet - Wilfredo’s Ice Cream Co.
This spreadsheet was built to ascertain how much the business should
charge for its ice cream. It tied in with the company’s finances to show profit, from input costs of the ice cream, ongoing expenses, and cost price charged. Ultimately it gave the managers insight into the sustainability of the ice cream business model and substantial amounts of money by showing that ultimately the business wasn’t sustainable.

** Home budget spreadsheet tool
Bruce designed a home budget tool to keep track of expenses and show deviations in a tight household budget. This can be adapted for business use. The next step is to code all the concepts and ultimately to tie it in to an R or Julia package so that everyone can use it.

** Investment analysis scripted document
Bruce wrote an experimental org script in Emacs to pull stock prices off the internet, and to reflect the valuations on investments. Bruce further incorporated exchange rates. Bruce stored crucial values to a Sqlite3 database and charted the continuously updated data with a time series chart from R. He has also converted some of the code to R and is performing optimisations on portfolios with some of the specialist packages in R (FRAPO, Quantmod, fPortfolio).

** Media monitoring analysis
Bruce developed a spreadsheet analytic tool that enabled a PR consultant to accurately monitor and analyse the spread, volume and value of media coverage received for her clients.

* TRAITS

- Excellent written communicator
- Expert problem solver 
- Technically orientated
- Analytical thinker
- An independent worker
    

References on request
