#+TITLE: Curriculum Vitae
#+OPTIONS: toc:nil
#+LaTeX_CLASS: koma-article
#+AUTHOR: Bruce R Graham
#+OPTIONS: -:nil

* CONTACT
- Email bruceg72@protonmail.ch

- Cell 0027-72-091-6687

* SUMMARY

Bruce is a science graduate in Operational Research and Maths through UNISA. 

Bruce has been an ardent Open Source Unix enthusiast since Linus Torvalds announced his new kernel. He has tinkered with device drivers on FreeBSD in C

Bruce has made scores of installations with various flavours of Linux, OpenBSD and FreeBSD. He has also built dozens of systems for home use.

Bruce has developed expertise in Bash and R and has programmed in PostgreSQL, C and Python.


       
* PROJECTS
** Compiling a kernel

Bruce compiled the 2.18 kernel tweaking the device drivers and fitting the available drivers. On numerous occassions Bruce compiled a full monolithic kernel and successfully ran his machine.

** Constructing a PC

Bruce constructed his own Linux systems, researching required hardware and available drivers.

** Experimenting with hardware

Bruce installed a picoITX form factor PC using a 12V DC ATX power supply in his caravan.

** Tweaking kernel drivers

Bruce tweaked the FreeBSD USB driver to pick up his USB device which had an unknown bluetooth IC and an unusual signature.

** Lithographic etching

Bruce used lithographic principles to etch his own hand made circuit board.

** Analysing in R

Bruce conducted a 'from scratch' analysis of his expenses in R, attempting to incorporate work from his actuarial studies on ruin theory.

** Making a Shiny dashboard

Bruce made various attempts at creating an insightful Dashboard for his portfolio of equities.
       
* EDUCATION

Honours Bachelor of Science (Incomplete)		[2005-01-31] to [2006-11-30]
Operational Research
University of South Africa, Pretoria

Bachelor of Science					[1993-01-31] to [2004-10-31]
Operational Research, Mathematics, Statistics (2:2)
University of South Africa, Pretoria

* TRAITS

+ [X] Excellent written communicator
+ [X] Great problem solver on Linux 
+ [X] Technically orientated
+ [X] An analytical thinker and
+ [X] An independent worker
 
* SKILLS
  
| Skill         | Level          |
|---------------+----------------|
| R             | senior         |
| Python        | intermediate   |
| Ansible       | beginner       |
| deb           | working        |
| rpm           | working        |
| Git           | working        |
| Bash          | working        |
| Command line  | expert         |
| Ubuntu        | senior         |
| CentOS        | senior         |
| PostgreSQL    | intermediate   |
| C             | senior         |
| Apache config | intermediate   |
| Shiny         | beginner/inter |
| Latex         | working        |



* WORK EXPERIENCE

Personal investment manager				     2017-01 to present
Work from home
Bruce conducts research and reading on the markets and economy with an eye to harnessing ultra long term market forces and trends. Bruce has become a connoisseur of investment products with excellent risk management and is not a return chaser.
  
Entrepreneur   		                             2008-04 to 2015-07
Wilfredo’s Ice Cream Company
Bruce performed product R&D and established a factory. He also researched a ﬁnancial reporting system and performed the bookkeeping. With his business partner, they produced ice cream and delivered it. Bruce administered the business and guided the direction of the business, spending his free time building a spreadsheet model to anticipate cashflow and profitability of the business.

Entrepreneur  		                             2006-09 to 2008-01
Karoo Wireless
Bruce was involved in the pilot phase of this business. He scoured the surrounding mountains for antennae sights. He lobbied the municipality for support. He canvassed the area for customers and lobbied for business. Bruce formed a partnership with a company in George to perform the technical setup. Bruce left after having secured the first few customers.



* REFERENCES

On request


  
