#+TITLE: Curriculum Vitae
#+OPTIONS: toc:nil
#+LaTeX_CLASS: article
#+AUTHOR: Bruce R Graham
#+EMAIL: bruce.graham@gmail.com

email: bruce.graham@gmail.com
cellular: 0027-72-091-6687


* SUMMARY

Bruce is a science graduate in Operational Research and Statistics through UNISA. 
He has been an ardent Open Source Unix enthusiast since Linus Torvalds announced his new kernel in 1991 and he has tinkered with device drivers on FreeBSD in C.
Bruce has made scores of installations with various flavours of Linux, OpenBSD and FreeBSD. He has also built dozens of systems for home use.
In the last decade Bruce was involved with a niche ice cream startup in Cape Town.
Bruce has subsequently spent time at home managing his investment fund and raising his family, who includes a daughter with special needs.
Bruce is looking for a remote role in system administration or devops. 

* PROJECTS

*Kernel compilation*
Bruce compiled the 2.18 kernel, configuring and fitting the device drivers to the available hardware. On numerous occassions Bruce compiled a full  monolithic kernel and successfully ran his machine.
 
*PC construction*
Bruce constructed his own PC systems, researching hardware  and availability of drivers on different platforms.
  
*Kernel driver tweaking*
Bruce tweaked the FreeBSD USB wireless driver to pick up his USB device which had an unknown bluetooth IC and an unusual signature.

*PCB Lithographic etching*
Bruce used lithographic principles to etch his own hand made circuit board.

* TRAITS 

✓ A written communicator \\
✓ A practised problem solver on Linux \\
✓ Technically oriented \\
✓ Analytical \\
✓ Disciplined and independent\\
✓ Productive behind a screen\\


* EDUCATION
Bachelor of Science 1993-2004 Operational Research, Statistics (2:2) UNISA

* WORK EXPERIENCE

2017 to Present - Bruce conducts research and reading on the markets and economy from home with an eye to harnessing ultra long term market forces and trends. 
2015-2016 Bruce also handled the end of year AFS and guided the direction of the Wilfredo's Ice Cream Company (WICC).\\
2012-2014 Bruce administered WICC. He issued invoices, handled incoming invoices, made payments, updated the books and handled the VAT.\\
2011 Performed product R&D and researched manufacture and delivery options. Also researched a ﬁnancial reporting system.\\

References on request


  
